services:
  ess-queue-ess:
    build: .
    ports:
      - "9324:9324"
    environment:
      - PORT=9324
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml:ro
    command: ["./ess-queue-ess", "--config", "/app/config.yaml"]
    container_name: ess-queue-ess
    networks:
      - shared-network

networks:
  shared-network:
    external: true
